/**
 * Auto-generated Asset Type Definitions
 *
 * This file is automatically generated from manifest.json.
 * DO NOT EDIT MANUALLY - run "pnpm manifest:generate" to regenerate.
 *
 * Generated: 2026-02-06T14:37:57.233Z
 */

/**
 * Supported asset types
 */
export type AssetType = 'texture' | 'spritesheet' | 'spine' | 'audio' | 'audioSprite' | 'json' | 'font';

/**
 * Texture asset keys
 * @example
 * // Common textures:
 * // - '3_Post_intro'
 * // - 'AUTOSPIN'
 * // - 'AUTOSPIN_disabled'
 * // - 'AUTOSPIN_mouse-ver'
 * // - 'AUTOSPIN_pressed'
 * // ... and 86 more
 */
export type TextureAssetKey = '3_Post_intro' | 'AUTOSPIN' | 'AUTOSPIN_disabled' | 'AUTOSPIN_mouse-ver' | 'AUTOSPIN_pressed' | 'BUY_FREE_SPINS' | 'Background' | 'Background_portrait' | 'Band' | 'FAST_PLAY' | 'FAST_PLAY_disabled' | 'FAST_PLAY_mouse-ver' | 'FAST_PLAY_pressed' | 'Foreground_left' | 'Foreground_p_left' | 'Foreground_p_right' | 'Foreground_portrait' | 'Foreground_right' | 'Free_Spin_Board' | 'Home' | 'Home_disabled' | 'Home_mouse-ver' | 'Home_pressed' | 'I' | 'I_disabled' | 'I_mouse-ver' | 'I_pressed' | 'Left_arrow' | 'Left_arrow_disabled' | 'Left_arrow_mouse-ver' | 'Left_arrow_pressed' | 'LoadingScreenBg' | 'LoadingScreenBg_Portrait' | 'Loading_Bar' | 'Locker' | 'Locker_Reflection' | 'Logo' | 'Logo_Portrait' | 'Midground' | 'Midground_left' | 'Midground_right' | 'Mockup_Landscape' | 'Mockup_Loading_screen_Landscape' | 'Mockup_Loading_screen_Portrait' | 'Mockup_Portait' | 'Reel' | 'Right_arrow' | 'Right_arrow_disabled' | 'Right_arrow_mouse-ver' | 'Right_arrow_pressed' | 'SOUND_OFF' | 'SOUND_OFF_disabled' | 'SOUND_OFF_mouse-ver' | 'SOUND_OFF_pressed' | 'SOUND_ON' | 'SOUND_ON_disabled' | 'SOUND_ON_mouse-ver' | 'SOUND_ON_pressed' | 'SPIN' | 'SPIN_disabled' | 'SPIN_mouse-ver' | 'SPIN_pressed' | 'STOP' | 'STOP_disabled' | 'STOP_mouse-ver' | 'STOP_pressed' | 'TURBO_OFF' | 'TURBO_OFF_disabled' | 'TURBO_OFF_mouse-ver' | 'TURBO_OFF_pressed' | 'TURBO_ON' | 'TURBO_ON_disabled' | 'TURBO_ON_mouse-ver' | 'TURBO_ON_pressed' | 'balance' | 'bet' | 'loading' | 'symbols/10' | 'symbols/9' | 'symbols/A' | 'symbols/Bronze_Piggy' | 'symbols/Gold_Piggy' | 'symbols/J' | 'symbols/K' | 'symbols/Q' | 'symbols/Rose_Gold_Piggy' | 'symbols/SCATTER' | 'symbols/Silver_Piggy' | 'symbols/WILD' | 'symbols/high_payout_1_1x' | 'win';

/**
 * Spritesheet asset keys
 */
export type SpritesheetAssetKey = never;

/**
 * Spine asset keys
 */
export type SpineAssetKey = never;

/**
 * Audio asset keys
 */
export type AudioAssetKey = never;

/**
 * Audio sprite asset keys
 */
export type AudioSpriteAssetKey = never;

/**
 * Audio sprite clip keys (individual sounds within audio sprites)
 */
export type AudioSpriteClipKey = never;

/**
 * JSON asset keys
 */
export type JsonAssetKey = 'post_intro_assets_1x' | 'sprites/sfx_sprite' | 'symbols/Gold_Piggy/gold_piggy' | 'symbols/Rose_Gold_Piggy/rose_gold_piggy' | 'symbols/Scatter/scatter' | 'symbols/Silver_Piggy/silver_piggy' | 'symbols/Wild/wild' | 'symbols/bronze_piggy_anim/bronze_piggy' | 'symbols/high_payout_1' | 'symbols/royals_anim/royels_akqj109' | 'uiPanels_0__1x';

/**
 * Font asset keys
 */
export type FontAssetKey = 'fonts/MotleyForces';

/**
 * All asset keys
 */
export type AssetKey = TextureAssetKey | SpritesheetAssetKey | SpineAssetKey | AudioAssetKey | AudioSpriteAssetKey | JsonAssetKey | FontAssetKey;

/**
 * Asset entry definition
 */
export interface AssetEntry {
  /** Unique asset key */
  key: AssetKey;
  /** Asset type */
  type: AssetType;
  /** Primary URL (relative to baseUrl) */
  url: string;
  /** Additional URLs (e.g., for spine: atlas, json) */
  urls?: Record<string, string>;
  /** Optional metadata */
  meta?: Record<string, unknown>;
}

/**
 * Asset bundle
 */
export interface Bundle {
  name: string;
  priority: number;
  required: boolean;
  assets: AssetEntry[];
}

/**
 * Complete asset manifest
 */
export interface Manifest {
  version: string;
  baseUrl: string;
  bundles: Bundle[];
}

/**
 * Audio sprite definition
 */
export interface AudioSprite {
  src: string[];
  sprite: Record<string, [number, number]>;
}

/**
 * Audio sprite clip timing information
 * Format: [startTimeMs, durationMs]
 */
export interface AudioSpriteClip {
  /** Start time in milliseconds */
  start: number;
  /** Duration in milliseconds */
  duration: number;
}

/**
 * Audio sprite timing data - provides type-safe access to clip timings
 */
export const AudioSpriteTimings = {} as const;

export function getAudioSpriteTiming(spriteKey: AudioSpriteAssetKey, clipKey: AudioSpriteClipKey): AudioSpriteClip | undefined {
  return undefined;
}

/**
 * Type-safe asset key getters by type
 * Use these for autocomplete suggestions: AssetKeys.texture, AssetKeys.audio, etc.
 */
export const AssetKeys = {
  /** Texture asset keys - 91 total */
  texture: ['3_Post_intro', 'AUTOSPIN', 'AUTOSPIN_disabled', 'AUTOSPIN_mouse-ver', 'AUTOSPIN_pressed', 'BUY_FREE_SPINS', 'Background', 'Background_portrait', 'Band', 'FAST_PLAY', 'FAST_PLAY_disabled', 'FAST_PLAY_mouse-ver', 'FAST_PLAY_pressed', 'Foreground_left', 'Foreground_p_left', 'Foreground_p_right', 'Foreground_portrait', 'Foreground_right', 'Free_Spin_Board', 'Home', 'Home_disabled', 'Home_mouse-ver', 'Home_pressed', 'I', 'I_disabled', 'I_mouse-ver', 'I_pressed', 'Left_arrow', 'Left_arrow_disabled', 'Left_arrow_mouse-ver', 'Left_arrow_pressed', 'LoadingScreenBg', 'LoadingScreenBg_Portrait', 'Loading_Bar', 'Locker', 'Locker_Reflection', 'Logo', 'Logo_Portrait', 'Midground', 'Midground_left', 'Midground_right', 'Mockup_Landscape', 'Mockup_Loading_screen_Landscape', 'Mockup_Loading_screen_Portrait', 'Mockup_Portait', 'Reel', 'Right_arrow', 'Right_arrow_disabled', 'Right_arrow_mouse-ver', 'Right_arrow_pressed', 'SOUND_OFF', 'SOUND_OFF_disabled', 'SOUND_OFF_mouse-ver', 'SOUND_OFF_pressed', 'SOUND_ON', 'SOUND_ON_disabled', 'SOUND_ON_mouse-ver', 'SOUND_ON_pressed', 'SPIN', 'SPIN_disabled', 'SPIN_mouse-ver', 'SPIN_pressed', 'STOP', 'STOP_disabled', 'STOP_mouse-ver', 'STOP_pressed', 'TURBO_OFF', 'TURBO_OFF_disabled', 'TURBO_OFF_mouse-ver', 'TURBO_OFF_pressed', 'TURBO_ON', 'TURBO_ON_disabled', 'TURBO_ON_mouse-ver', 'TURBO_ON_pressed', 'balance', 'bet', 'loading', 'symbols/10', 'symbols/9', 'symbols/A', 'symbols/Bronze_Piggy', 'symbols/Gold_Piggy', 'symbols/J', 'symbols/K', 'symbols/Q', 'symbols/Rose_Gold_Piggy', 'symbols/SCATTER', 'symbols/Silver_Piggy', 'symbols/WILD', 'symbols/high_payout_1_1x', 'win'] as const satisfies readonly TextureAssetKey[],
  /** Spritesheet asset keys - 0 total */
  spritesheet: [] as const satisfies readonly SpritesheetAssetKey[],
  /** Spine asset keys - 0 total */
  spine: [] as const satisfies readonly SpineAssetKey[],
  /** Audio asset keys - 0 total */
  audio: [] as const satisfies readonly AudioAssetKey[],
  /** Audio sprite asset keys - 0 total */
  audioSprite: [] as const satisfies readonly AudioSpriteAssetKey[],
  /** JSON asset keys - 11 total */
  json: ['post_intro_assets_1x', 'sprites/sfx_sprite', 'symbols/Gold_Piggy/gold_piggy', 'symbols/Rose_Gold_Piggy/rose_gold_piggy', 'symbols/Scatter/scatter', 'symbols/Silver_Piggy/silver_piggy', 'symbols/Wild/wild', 'symbols/bronze_piggy_anim/bronze_piggy', 'symbols/high_payout_1', 'symbols/royals_anim/royels_akqj109', 'uiPanels_0__1x'] as const satisfies readonly JsonAssetKey[],
  /** Font asset keys - 1 total */
  font: ['fonts/MotleyForces'] as const satisfies readonly FontAssetKey[],
} as const;

/**
 * Get asset key suggestions for autocomplete (auto-generated from asset-suggestions.json)
 * @param type - Asset type to get suggestions for
 * @param partialKey - Optional partial key to filter suggestions
 * @returns Array of suggested asset keys
 * @example
 * // Get all texture suggestions
 * getAssetSuggestions("texture")
 * // Get texture suggestions matching "cell"
 * getAssetSuggestions("texture", "cell")
 */
export function getAssetSuggestions(type: AssetType, partialKey?: string): string[] {
  try {
    // Try to load from auto-generated suggestions
    const suggestions = require("../tools/asset-suggestions.json");
    if (partialKey) {
      const lower = partialKey.toLowerCase();
      return Object.keys(suggestions.assets || {})
        .filter(key => {
          const asset = suggestions.assets[key];
          return asset.type === type && key.toLowerCase().includes(lower);
        })
        .sort((a, b) => {
          const aStarts = a.toLowerCase().startsWith(lower);
          const bStarts = b.toLowerCase().startsWith(lower);
          if (aStarts && !bStarts) return -1;
          if (!aStarts && bStarts) return 1;
          return a.length - b.length;
        })
        .slice(0, 20);
    }
    return Object.keys(suggestions.assets || {})
      .filter(key => suggestions.assets[key].type === type);
  } catch {
    // Fallback to AssetKeys if suggestions file not available
    const keys = AssetKeys[type] || [];
    if (!partialKey) return [...keys];
    const lower = partialKey.toLowerCase();
    return keys.filter(k => k.toLowerCase().includes(lower));
  }
}

/**
 * Get related assets for a given key (auto-generated suggestions)
 * @param key - Asset key to find related assets for
 * @returns Array of related asset keys
 */
export function getRelatedAssets(key: AssetKey): AssetKey[] {
  try {
    const suggestions = require("../tools/asset-suggestions.json");
    return (suggestions.relatedAssets?.[key] || []).filter(k => {
      // Verify the related asset exists in AssetKeys
      return Object.values(AssetKeys).flat().includes(k as AssetKey);
    }) as AssetKey[];
  } catch {
    return [];
  }
}

/**
 * Get assets by category (auto-generated from patterns)
 * @param category - Category name
 * @returns Array of asset keys in that category
 */
export function getAssetsByCategory(category: string): AssetKey[] {
  try {
    const suggestions = require("../tools/asset-suggestions.json");
    return (suggestions.categories?.[category] || []).filter(k => {
      return Object.values(AssetKeys).flat().includes(k as AssetKey);
    }) as AssetKey[];
  } catch {
    return [];
  }
}

/**
 * Type guards for asset types
 */
export function isTextureAsset(key: AssetKey): key is TextureAssetKey {
  return AssetKeys.texture.includes(key as TextureAssetKey);
}

export function isSpritesheetAsset(key: AssetKey): key is SpritesheetAssetKey {
  return AssetKeys.spritesheet.includes(key as SpritesheetAssetKey);
}

export function isSpineAsset(key: AssetKey): key is SpineAssetKey {
  return AssetKeys.spine.includes(key as SpineAssetKey);
}

export function isAudioAsset(key: AssetKey): key is AudioAssetKey {
  return AssetKeys.audio.includes(key as AudioAssetKey);
}

export function isAudioSpriteAsset(key: AssetKey): key is AudioSpriteAssetKey {
  return AssetKeys.audioSprite.includes(key as AudioSpriteAssetKey);
}

export function isJsonAsset(key: AssetKey): key is JsonAssetKey {
  return AssetKeys.json.includes(key as JsonAssetKey);
}

export function isFontAsset(key: AssetKey): key is FontAssetKey {
  return AssetKeys.font.includes(key as FontAssetKey);
}